gpu_index: 0
data:
  dataset: pamap2
  num_sensors: 6
  wandb: False

model:
  save_path: C:\\Users\\lahir\\data\\atomicHAR\\models\\
  epochs: 10
  seq_model: BLSTM #transformer or BLSTM or cnn

utdmhad:
  path: C:\\Users\\lahir\\data\\UTD_MHAD\\
  imu_seg: True
  train:
    bs: 32
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [1, 2, 3, 4, 5,6, 7]
  test:
    bs: 1
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [8]
  model:
    transformer: 
      d_model: 4
      num_layers: 1
      n_head: 4
      dropout: 0.2
      dim_feedforward: 64
      d_out: 32
    cnn:
      in_channels: 6
      #imu_feat_dim must be divisible by 4
      imu_feat_dim: 32
      atom_emb_dim: 16
    forcast:
      hidden_dim: 20
pamap2:
  path: C:\\Users\\lahir\\data\\pamap2+physical+activity+monitoring\\PAMAP2_Dataset\\PAMAP2_Dataset\\
  data_types: ['Protocol']
  normalize: True
  split: 0.8 #train:test split. Only appicable when there is an overlap between train and test subjects
  group1: [101,102,103]
  group2: [104,105,106]
  group3: [107,108,109]
  train_ac: [1,3,4,5,12,16,24]
  train_subj: [group1,group2,group3]
  test_subj: [group2]
  FSL:
    test_subj: [group1]
    test_ac: [2,6,7,13,17]
    inv_overlap: 1 #(1-overlap) between the windows. i.e 1 for no overlap, 0.5 for 50% overlap
    n_shot: 5
  train_bs: 32
  test_bs: 32
  window_len_s: 1
  inv_overlap: 0.5
  sample_freq: 100
  model:
    atoms:
      #atomic HAR configs
      num_indices: 1  #number of max indices to use per sequence
      #the sequence length = num_indices * num_atoms (i.e the number of filters in the last cnn layer)
      atm_occur: 4 # how many instances of the same atom are allowed to occur in the same sequence
      hide_frac: 0.5 #max fraction of atoms to hide each time
    BLSTM:
      hidden_size: 64
      num_layers: 1
      dense: 64
    transformer: 
      d_model: 64
      num_layers: 1
      n_head: 4
      dropout: 0.2
      dim_feedforward: 64
      d_out: 32
    cnn:
      in_channels: 36
      channels1: 64
      dropout: 0.2
      channels2: 32
      kernel_size1: 3
      kernel_size2: 7
      kernel_size3: 11
      num_cls_features: 128
      #imu_feat_dim must be divisible by 4
      imu_feat_dim: 32
      atom_emb_dim: 16
      num_atoms: 64
    forcast:
      hidden_dim: 20
