db:
  driver: mysql
  user: omry
  pass: secret
data:
  dataset: utdmhad
  num_sensors: 6
model:
  save_path: C:\\Users\\lahir\\data\\atomicHAR\\models\\model.pth

utdmhad:
  path: C:\\Users\\lahir\\data\\UTD_MHAD\\
  imu_seg: True
  train:
    bs: 3
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [1, 2, 3, 4, 5]
  test:
    bs: 1
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [6, 7, 8]
  model:
    transformer: 
      d_model: 4
      num_layers: 1
      n_head: 4
      dropout: 0.2
      dim_feedforward: 64
      d_out: 32
    cnn:
      in_channels: 6
