data:
  dataset: pamap2
  num_sensors: 6
  wandb: False

model:
  save_path: C:\\Users\\lahir\\data\\atomicHAR\\models\\model.pth
  epochs: 100000

utdmhad:
  path: C:\\Users\\lahir\\data\\UTD_MHAD\\
  imu_seg: True
  train:
    bs: 32
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [1, 2, 3, 4, 5,6, 7]
  test:
    bs: 1
    actions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    subjects: [8]
  model:
    transformer: 
      d_model: 4
      num_layers: 1
      n_head: 4
      dropout: 0.2
      dim_feedforward: 64
      d_out: 32
    cnn:
      in_channels: 6
      #imu_feat_dim must be divisible by 4
      imu_feat_dim: 32
      atom_emb_dim: 16
    forcast:
      hidden_dim: 20
pamap2:
  path: C:\\Users\\lahir\\data\\pamap2+physical+activity+monitoring\\PAMAP2_Dataset\\PAMAP2_Dataset\\
  data_types: ['Protocol']
  train_subj: [101,102,103]
  # train_subj: [101,102,103,104,105,106,109]
  test_subj: [101,102,103]
  train_ac: [0,1,2,3,4,5]
  # train_ac: [0,1,2,3,4,5,6,7,8,9,10,11]
  test_ac: [0,1,2,3,4,5]
  train_bs: 32
  test_bs: 32
  window_len_s: 1
  overlap: 0.5
  sample_freq: 100
  model:
    transformer: 
      d_model: 16
      num_layers: 1
      n_head: 4
      dropout: 0.2
      dim_feedforward: 64
      d_out: 32
    cnn:
      in_channels: 6
      #imu_feat_dim must be divisible by 4
      imu_feat_dim: 32
      atom_emb_dim: 16
    forcast:
      hidden_dim: 20
